# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import onnxmodel_pb2 as onnxmodel__pb2


class InferencerStub(object):
    """The inference service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeInference = channel.unary_unary(
                '/onnxmodel.Inferencer/MakeInference',
                request_serializer=onnxmodel__pb2.InferenceRequest.SerializeToString,
                response_deserializer=onnxmodel__pb2.Prediction.FromString,
                )


class InferencerServicer(object):
    """The inference service definition
    """

    def MakeInference(self, request, context):
        """serves an inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferencerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeInference': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeInference,
                    request_deserializer=onnxmodel__pb2.InferenceRequest.FromString,
                    response_serializer=onnxmodel__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onnxmodel.Inferencer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inferencer(object):
    """The inference service definition
    """

    @staticmethod
    def MakeInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onnxmodel.Inferencer/MakeInference',
            onnxmodel__pb2.InferenceRequest.SerializeToString,
            onnxmodel__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
